#! /bin/tcsh

set sim=0


while($sim<11)


echo $sim
/Users/divyansh/bin/nrn "/Users/divyansh/lab_work/Noise_oscillations/Noise_Osc_july.hoc"  << here >& "dOSC_Terminal$sim.txt" 
Final_run($sim) 
quit()
here

@ sim+=1

end



